version: '3.1'

services:
  backend:
    container_name: Backend
    restart: always
    build:
      context: ./coloc
      dockerfile: Dockerfile
    ports:
      - '5656:5656'
    volumes:
            - ./coloc:/var/www/html
            - ./coloc/vhost:/etc/apache2/sites-enabled
    networks:
      - colocflow
            
  mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

  db:
    container_name: Database
    image: 'mariadb'
    restart: always
    environment:
      MYSQL_DATABASE: data
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # Pour lancer un dump automatiquement au montage du conteneur
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - colocflow

  phpmyadmin:
    container_name: PhpMyAdmin
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      PMA_HOST: db
    networks:
      - colocflow

  nuxt-app:
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    volumes:
      - ./Frontend/:/usr/app
      - ./Frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    networks:
      - colocflow


networks:
  colocflow:
    driver: bridge