version: '3.1'

services:
  backend:
    container_name: Backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - '5656:80'
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
    command: sh -c "composer install"
    restart: always

  db:
    container_name: Database
    image: 'mariadb'
    restart: always
    environment:
      MYSQL_DATABASE: data
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # Pour lancer un dump automatiquement au montage du conteneur
      - ./backend/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    container_name: PhpMyAdmin
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1

  nuxt-app:
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    volumes:
      - ./Frontend/:/usr/app
      - ./Frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
